version: '3.8'

services:
  web:
    build:
      context: FastAPI/
      dockerfile: Dockerfile
    container_name: web
    volumes:
      - ./FastAPI:/FastAPI
    ports:
      - "8000:80"
    environment:
      - "DATABASE_URL=sqlite:///db.sqlite"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./public:/usr/share/nginx/html
