version: '3.8'

services:
  web:
    build:
      context: FastAPI/
      dockerfile: Dockerfile
    container_name: web
    volumes:
      - ./FastAPI:/FastAPI
    ports:
      - "80:80"
#    depends_on:
#      - db
#    links:
#      - db
    environment:
#      - DATABASE_URL=postgresql://postgres_user:postgres_password@db:5432/example_db
      - "DATABASE_URL=sqlite:///db.sqlite"
      - "SUPERUSER_LOGIN=admin"
      - "SUPERUSER_PASSWD=password"

#  db:
#    image: postgres:latest
#    container_name: postgres
#    volumes:
#      - ./postgres:/var/lib/postgresql/data/
#    expose:
#      - 5432
#    environment:
#      - POSTGRES_USER=postgres_user
#      - POSTGRES_PASSWORD=postgres_password
#      - POSTGRES_DB=what_did_you_forget_today
